cms:
    resource: "@CMSBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path: /login
    defaults:
        _controller: CMSBundle:Security:login


login_check:
    path: /login_check

logout:
    path: /logout