security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    mik:
                        password: mikpass
                        roles: 'ROLE_USER'
                    admin:
                        password: kraken
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
            #algorithm: bcrypt
            # Everything worked up until I added line 19, 20
            #Encoder used       Symfony\Component\Security\Core\Encoder\PlaintextPasswordEncoder
            #Encoded password   kraken{OoP+2jYKE1pQM1DLMixkFjpj2MhHWl1SLFUM5/xP}
            #Generated salt     OoP+2jYKE1pQM1DLMixkFjpj2MhHWl1SLFUM5/xP

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /cms/user, roles: ROLE_ADMIN }
        - { path: /cms/category, roles: ROLE_ADMIN }
        - { path: /cms/page, roles: ROLE_USER }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }