# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig.disqus_extension:
            class: Framaru\CMSBundle\Service\DisqusExtension
            public: false
            arguments: ["@twig", "@router.default", "%disqus%"]
            tags:
                - { name: twig.extension }